### ISSUE TITLE
Add copyright export to fo_nomos_license_list

### ISSUE THREAD

**Issue by GMishx** [fossology/fossology#1715]
### Description

With the PR #1713, the UI can export Copyright list as well.

It would be nice to have the CLI do it as well.

#### Steps followed and expected result

Check #1713

**Comment by HeroicHitesh** [comment]
@GMishx I guess this issue is fixed in #1713 so it can be closed to avoid any confusion.

**Comment by GMishx** [comment]
@HeroicHitesh the feature is still not there in master, neither a PR exists. The issue thus still exists.

**Comment by ArijeetBanerjee** [comment]
Hey there 
It would be an honor to work in this issue
If it is still available, I'd be glad to work in it

**Comment by SalmanDeveloperz** [comment]
Hey, Is this issue still opened?

**Comment by SalmanDeveloperz** [comment]
Hey @GMishx , Can I work on this issue?

**Comment by ritikishere** [comment]
PR is ready for review. Waiting for workflow checks to complete and maintainer approval.  

The issue has been solved in #3216 .

**Comment by atharva-nagane** [comment]
Hi, I’ve set up FOSSology locally using the Docker setup and started looking into this issue.

I noticed that PR #3216 attempted to add CSV export functionality for the CLI tool `fo_nomos_license_list`, but it was closed without merge. I’m currently reviewing both the original implementation and the changes from that PR to understand what adjustments might be needed.

If the issue is still open, I’d like to investigate it further and attempt a fix. @GMishx

**Comment by sunkireddy-Barath** [comment]
Hi @GMishx ,I’m excited to contribute to this issue. Could you please assign this task to me?

**Comment by adishchowdhury** [comment]
Hi can I work on this issue?
