### ISSUE TITLE
REST API: Allow copyright export

### ISSUE THREAD

**Issue by GMishx** [fossology/fossology#1716]
### Description

With PR #1713, the class `UIExportList` can export copyrights as well. Since the REST API uses the call to get license list, an option to export copyright list can be added as well.

#### Steps followed and expected result

Check #1713
Check #1608

**Comment by HeroicHitesh** [comment]
@GMishx I guess we can close this too as it's resolved in #1713

**Comment by GMishx** [comment]
@HeroicHitesh , the issue to provide a REST API endpoint which can generate similar results as the UI merged by #1713 and it is still not done.

**Comment by ananthmallarapu** [comment]
@GMishx , is there any plan in releasing this functionality from API ? can you recommend a alternate way to get the copyright list exported in an automated way .

**Comment by GMishx** [comment]
Hi @ananthmallarapu , there is no plan as of now to implement this functionality.

For alternative way, you can have a look on SPDX reports which are more computer friendly rather than unified report.

**Comment by ArijeetBanerjee** [comment]
Hey there 
It would be an honor to work in this issue
If it is still available, I'd be glad to work in it

**Comment by pigeio** [comment]
Hi @GMishx and team,
I was looking for backend API issues and found this one. I noticed it's been open for a while, but the feature (exporting copyrights via API) seems valuable for automation.
Since the project is moving towards Go, would it be better to implement this as a new endpoint in the Go microservices architecture rather than the legacy PHP API?
I have experience with Go and would love to pick this up if it's still relevant.

**Comment by ritikishere** [comment]
Hi @GMishx 👋  
I noticed this issue is still open and marked as a good first issue.

I’d like to work on adding a REST API endpoint to export copyrights
(similar to the UI functionality added in #1713).

Before starting, I wanted to confirm:
- Is this still something the maintainers would accept?
- Are there any design/API considerations I should follow?

Thanks!

**Comment by abdollahShahid** [comment]
Hi maintainers, PR #3222 fixes the export-list copyright response format for this issue. Tested with PHP lint locally; CI will run the full test suite.
