### ISSUE TITLE
License Browser view update extremely slow in 3.8.1

### ISSUE THREAD

**Issue by rlintu** [fossology/fossology#1798]
### Description

License Browser view is extremely slow for large packages (~100k files) in 3.8.1. The slowness is visible in a production scale database where there are millions of items and clearing_decisions. 

#### How to reproduce

Open the large package using the web UI.

#### Possible cause of the problem

 I identified the problem in `www/ui/async/AjaxExplorer.php` file. When I used 3.5.0 version of `AjaxExplorer.php` the update time reduced from 56s to about 20s for a GCC package. FOSSology has always been very slow but now version 3.8.1 is almost unusable.

### Versions

FOSSology: 3.8.1
Ubuntu 18.04

**Comment by rlintu** [comment]
When I checked the database using `SELECT pid, datname, usename, query FROM pg_stat_activity;` command then very often the following query was on execution:

``` 
WITH allDecs AS (
   SELECT
     cd.clearing_decision_pk AS id,
     cd.pfile_fk AS pfile_id,            
     ut.uploadtree_pk AS itemid,  
     cd.user_fk AS user_id,               
     cd.decision_type AS type_id,     
     cd.scope AS scope,                   
     EXTRACT(EPOCH FROM cd.date_added) AS ts_added,     
     CASE cd.scope WHEN 1 THEN 1 ELSE 0 END AS scopesort  
   FROM clearing_decision cd         
     INNER JOIN uploadtree_a ut     
       ON (ut.pfile_fk = cd.pfile_fk AND cd.scope = 1)
         OR (ut.uploadtree_pk = cd.uploadtree_fk      
           AND cd.scope = 0 AND cd.group_fk = $3)  
   WHERE ut.upload_fk=$4 AND  ut.uploadtree_pk = $1 AND 
     cd.decision_type!=$2),                      
 decision AS (                                         
   SELECT DISTINCT ON(itemid) *            
   FROM allDecs                                      
   ORDER BY itemid, scopesort, id DESC   
 )  
 SELECT
   decision.*, 
   users.
```

**Comment by GMishx** [comment]
Hello @rlintu ,

We also observed the issue. I am trying to fix it in PR #1576

**Comment by GMishx** [comment]
hello @rlintu ,

We just merged #1576 with some improvements. Can you please check if it is working better for you with the latest master?

**Comment by dineshr93** [comment]
Hi @GMishx This issue still remains in the recent version 
fossology #82f63a41d   >3.10.0-rc1 (docker deployed)

Even for package for size 4 mb.



![image](https://user-images.githubusercontent.com/4498415/105173262-0fad5c00-5b21-11eb-8a16-8c26497ad783.png)

**Comment by dineshr93** [comment]
I am using maching Ubuntu 18.04, As you can see in the above pic I have 4 cores & one of cores hitting at 100 % usage (right) while this license browser page is processing to list down the source folder section(left).

**Comment by dineshr93** [comment]
I have installed the recent version in production & now I have been receiving complaints of slowness from them. I thought of sharing the screenshot cpu in case if it helps

**Comment by GMishx** [comment]
Hello @dineshr93 , that is very unfortunate. The high CPU usage should be because of database. Can you please share the link to the package? It will be helpful for us to investigate the issue.
Also, can you please check if there is some message in the docker log (from Apache)?

**Comment by dineshr93** [comment]
llvm 2.0 link that is scanned  https://releases.llvm.org/2.0/llvm-2.0.tar.gz

may I know how to access apache logs via docker?

**Comment by GMishx** [comment]
Thanks for proving the link to the package.

> may I know how to access apache logs via docker?

You can check it from the `docker logs` command for your container.

**Comment by GMishx** [comment]
Hello @dineshr93 ,
I just uploaded the llvm package on my local machine on latest master. The License Browser loaded in 1.68s.

![image](https://user-images.githubusercontent.com/18077542/106452346-c01a4900-64ad-11eb-9c4a-3376fe4f1365.png)

What I am suspecting from this result is that there is some issue with your DB and thus the ajax call is getting a 500 error. If that's the case, then
1. The table will never load
2. You can verify this from the network tab to check if the ajax call returned some error.
3. If there is error in the call, it should come up in the apache logs.
